### ISSUE TITLE
Alinhamento da toc

### ISSUE THREAD

**Issue by samuel-rosa** [samuel-rosa/UFRuralRJ#1]
Há um problema com o alinhamento dos itens de primeiro nível na toc, mas apenas com aqueles numerados. A versão estrelada, usada para as referências bibliográficas, apêndices e anexos, está sendo alinhada corretamente.

**Comment by dedekindbr** [comment]
Ok, vou dar uma olhada 

Em 09.07.2015 11:24, Alessandro Samuel-Rosa
escreveu: 

> Há um problema com o alinhamento dos itens de primeiro
nível na toc, mas apenas com aqueles numerados. A versão estrelada,
usada para as referências bibliográficas, apêndices e anexos, está sendo
alinhada corretamente. 
> 
> --
> Reply to this email directly or view
it on GitHub [1].

-- 

Alessandro Bandeira
Duarte
UFRRJ
www.alessandroduarte.com.br
[2]
http://grupofilosofiadamatematica.com.br
[3]
www.alessandroduarte.com.br/latex_e_linux [4]
(Usa
GNU/Linux)
"Colaborar atrai amigos, competir atrai inimigos
…"
ALESSANDRODUARTE@EKIGA.NET
HTTPS://QUITTER.SE/FREGEBR [5]




Links:
------
[1]
https://github.com/samuel-rosa/UFRuralRJ/issues/1
[2]
http://www.alessandroduarte.com.br
[3]
http://grupofilosofiadamatematica.com.br
[4]
http://webmail.alessandroduarte.com.br/www.alessandroduarte.com.br/latex_e_linux
[5]
https://quitter.se/fregebr

**Comment by dedekindbr** [comment]
Em geral, a numeração é assim: 

1 

 1.1 

 1.2 

 1.2.1 

Fiz
assim. É nisso que você estava pensando? 

Em 09.07.2015 14:53,
Alessandro Bandeira Duarte escreveu: 

> Ok, vou dar uma olhada 
> 
> Em
09.07.2015 11:24, Alessandro Samuel-Rosa escreveu: 
> 
>> Há um problema
com o alinhamento dos itens de primeiro nível na toc, mas apenas com
aqueles numerados. A versão estrelada, usada para as referências
bibliográficas, apêndices e anexos, está sendo alinhada corretamente.

>> 
>> --
>> Reply to this email directly or view it on GitHub [1].
>

> -- 
> 
> Alessandro Bandeira Duarte
> UFRRJ
>
www.alessandroduarte.com.br [2]
>
http://grupofilosofiadamatematica.com.br [3]
>
www.alessandroduarte.com.br/latex_e_linux [4]
> (Usa GNU/Linux)
>
"Colaborar atrai amigos, competir atrai inimigos …"
>
ALESSANDRODUARTE@EKIGA.NET
> HTTPS://QUITTER.SE/FREGEBR [5]

--


Alessandro Bandeira Duarte
UFRRJ
www.alessandroduarte.com.br
[2]
http://grupofilosofiadamatematica.com.br
[3]
www.alessandroduarte.com.br/latex_e_linux [4]
(Usa
GNU/Linux)
"Colaborar atrai amigos, competir atrai inimigos
…"
ALESSANDRODUARTE@EKIGA.NET
HTTPS://QUITTER.SE/FREGEBR [5]




Links:
------
[1]
https://github.com/samuel-rosa/UFRuralRJ/issues/1
[2]
http://www.alessandroduarte.com.br
[3]
http://grupofilosofiadamatematica.com.br
[4]
http://webmail.alessandroduarte.com.br/www.alessandroduarte.com.br/latex_e_linux
[5]
https://quitter.se/fregebr

**Comment by samuel-rosa** [comment]
Quanto eu compilo o documento, o sumário fica da seguinte maneira:

       1 INTRODUÇÃO
      1.1 SEÇÃO
      1.1.1 Subseção
       2 TÍTULO DO PRIMEIRO ARTIGO
      RESUMO
      ABSTRACT

Note que os itens de primeiro nível possuem indentação, ficando desalinhados em relação aos demais.

**Comment by dedekindbr** [comment]
Ah sim, acho que por causa dessa linha


@dottedtocline{0}{0em}{ii@chapnumindent}{MakeUppercase{#1}}{#2} 

%%
Espaço entre os pontos na linha
pontilhada
renewcommand@dotsep{1.5}

renewcommand*{l@chapter}[2]{

addpenalty{-@highpenalty}
 vskip -2.5ex @plusp@

setlength@tempdima{1.5em}
 begingroup
 parindent z@ rightskip
@pnumwidth
 parfillskip -@pnumwidth
 leavevmodebfseries

advanceleftskip@tempdima
 hskip -leftskip
 % esta é a definicao original
da classe report:
 %#1nobreakhfil nobreakhb@xt@@pnumwidth{hss #2}par

@dottedtocline{0}{0em}{ii@chapnumindent}{MakeUppercase{#1}}{#2}

penalty@highpenalty
 endgroup
} 

Em 09.07.2015 15:46, Alessandro
Samuel-Rosa escreveu: 

> Quanto eu compilo o documento, o sumário fica
da seguinte maneira: 
> 
> 1 INTRODUÇÃO
> 1.1 SEÇÃO
> 1.1.1 Subseção
> 2
TÍTULO DO PRIMEIRO ARTIGO
> RESUMO
> ABSTRACT
> 
> Note que os itens de
primeiro nível possuem indentação, ficando desalinhados em relação aos
demais. 
> 
> --
> Reply to this email directly or view it on GitHub
[1].

-- 

Alessandro Bandeira Duarte
UFRRJ
www.alessandroduarte.com.br
[2]
http://grupofilosofiadamatematica.com.br
[3]
www.alessandroduarte.com.br/latex_e_linux [4]
(Usa
GNU/Linux)
"Colaborar atrai amigos, competir atrai inimigos
…"
ALESSANDRODUARTE@EKIGA.NET
HTTPS://QUITTER.SE/FREGEBR [5]




Links:
------
[1]
https://github.com/samuel-rosa/UFRuralRJ/issues/1#issuecomment-120103159
[2]
http://www.alessandroduarte.com.br
[3]
http://grupofilosofiadamatematica.com.br
[4]
http://webmail.alessandroduarte.com.br/www.alessandroduarte.com.br/latex_e_linux
[5]
https://quitter.se/fregebr

**Comment by dedekindbr** [comment]
Encontrei uma solução, mas é um tanto porca 

%% Espaço entre o
número e o título dos itens de primeiro
nível
newlength{ii@chapnumindent}setlength{ii@chapnumindent}{1em}

%%
Espaço entre os pontos na linha
pontilhada
renewcommand@dotsep{1.5}

renewcommand*{l@chapter}[2]{

addpenalty{-@highpenalty}
 vskip -2.5ex @plusp@

setlength@tempdima{1.5em}
 begingroup
 parindent z@ rightskip
@pnumwidth
 parfillskip -@pnumwidth
 leavevmodebfseries

advanceleftskip@tempdima
 hskip -leftskip
 % esta é a definicao original
da classe report:
 %#1nobreakhfil nobreakhb@xt@@pnumwidth{hss #2}par

@DOTTEDTOCLINE{0}{-0.35EM}{II@CHAPNUMINDENT}{MAKEUPPERCASE{#1}}{#2}

penalty@highpenalty
 endgroup
} 

O ideal seria eliminar a indentação


Em 09.07.2015 15:46, Alessandro Samuel-Rosa escreveu: 

> Quanto eu
compilo o documento, o sumário fica da seguinte maneira: 
> 
> 1
INTRODUÇÃO
> 1.1 SEÇÃO
> 1.1.1 Subseção
> 2 TÍTULO DO PRIMEIRO ARTIGO
>
RESUMO
> ABSTRACT
> 
> Note que os itens de primeiro nível possuem
indentação, ficando desalinhados em relação aos demais. 
> 
> --
> Reply
to this email directly or view it on GitHub [1].

-- 

Alessandro
Bandeira Duarte
UFRRJ
www.alessandroduarte.com.br
[2]
http://grupofilosofiadamatematica.com.br
[3]
www.alessandroduarte.com.br/latex_e_linux [4]
(Usa
GNU/Linux)
"Colaborar atrai amigos, competir atrai inimigos
…"
ALESSANDRODUARTE@EKIGA.NET
HTTPS://QUITTER.SE/FREGEBR [5]




Links:
------
[1]
https://github.com/samuel-rosa/UFRuralRJ/issues/1#issuecomment-120103159
[2]
http://www.alessandroduarte.com.br
[3]
http://grupofilosofiadamatematica.com.br
[4]
http://webmail.alessandroduarte.com.br/www.alessandroduarte.com.br/latex_e_linux
[5]
https://quitter.se/fregebr

**Comment by samuel-rosa** [comment]
Sim, já havia tentado isso. Contudo, isso faz com que os capítulos estrelados (referências blibliográficas) sejam também deslocados (indentação negativa), ficando desalinhados. A solução seria, então, na linha 872 usar

       \ifchap\if@aftertoc\addcontentsline{toc}{chapter}{\hspace*{0.35em}#1}\fi\fi%

ao invés de

       \ifchap\if@aftertoc\addcontentsline{toc}{chapter}{#1}\fi\fi%

Essa solução porca deixa todo mundo alinhado, por enquanto!

**Comment by samuel-rosa** [comment]
Implementei essa solução rápida e suja!

**Comment by dedekindbr** [comment]
Interessante, aqui só desalinhou o apêndice




Em 09-07-2015 17:07, Alessandro Samuel-Rosa escreveu:

**Comment by dedekindbr** [comment]
https://github.com/dedekindbr/UFRuralRJ/commit/6af913cbfa0babbeb619b463b739e287b68376e1

Em 07/09/15 17:07, Alessandro Samuel-Rosa escreveu:

**Comment by dedekindbr** [comment]
Tem um outro problema em relação aos capítulos. Veja imagem




Era para ser apenas Capítulo I, mas aparece 2 Capítulo 1

É possível resolver esse problema no arquivos .tex por meio do \renewcommand

Em 07/13/15 14:03, Alessandro Samuel-Rosa escreveu:

**Comment by dedekindbr** [comment]
O comando é

\renewcommand{\thechapter}{}

Resultado




PS - coloquei o comando no arquivo chapter00.tex

Vou colocar na classe para ver o que acontece

**Comment by samuel-rosa** [comment]
Não estou vendo as imagens.

**Comment by samuel-rosa** [comment]
Creio que esteja falando do exemplo com capítulos individuais onde o primeiro capítulo (Capítulo I) aparece como item 2 do sumário (2 Capítulo I). Creio que esse seja o comportamento esperado, pois a introdução não é considerada como um capítulo. Vou checar no manual.

**Comment by dedekindbr** [comment]
Estou enviando a imagem como anexo (ao invés de inserir no corpo do texto)

No manual da rural, não deveria aparecer o número 2 antes de Capítulo 1

**Comment by dedekindbr** [comment]
Ok, esqueça o que disse. Estou vendo um modelo de tese e é assim que 
fica mesmo

**Comment by samuel-rosa** [comment]
O manual diz que (p.13):

     Os títulos das divisões principais ou seções primárias devem ser digitados em letras 
     maiúsculas e em negrito (ex.: 1 INTRODUÇÃO), centralizados, numerados em arábico, 
     sem pontuação, iniciando-se o texto após dois espaços.

Parece não haver definição exata para o caso de capítulos individuais. Contudo, se assumirmos que os capítulos sejam *divisões principais*, então eles são numerados com 1, 2, ...
